# Copia estos campos en los Secrets de Streamlit Cloud si activas LIVE.
# En modo PAPER no son necesarios.

# [binance]
# API_KEY = "..."
# API_SECRET = "..."
# PASSPHRASE = "..."  # si tu exchange la requiere

# Puedes mapearlos a variables de entorno en tu app si decides leerlos.
