# Copia estos campos en los Secrets de Streamlit Cloud si activas LIVE.
# En modo PAPER no son necesarios.

# [binance]
# API_KEY = "..."
# API_SECRET = "..."
# PASSPHRASE = "..."  # si tu exchange la requiere

# Fuente remota de métricas (opcional): si la defines, el dashboard leerá
# equity.csv y trades.csv desde esta URL base.
# Ejemplos:
# - Si usas el servicio Docker 'metrics' en tu VPS: "http://TU_HOST:8000/metrics"
# - Si publicas en otro lado: "https://tu-dominio.com/metrics"
# METRICS_BASE_URL = "http://localhost:8000/metrics"

# Fuente remota de precio (opcional): CSV con columnas [datetime, open, high, low, close, volume]
# Si usas el servicio Docker 'metrics': "http://TU_HOST:8000/price/BTCUSDT_1h.csv"
# PRICE_CSV_URL = "http://localhost:8000/price/BTCUSDT_1h.csv"

# Puedes mapearlos a variables de entorno en tu app si decides leerlos.
